Restructure the repo for WebView based rendering
MemoLanes/MemoLanes pull request #136
Opened 2024-11-21 11:30 UTC by tavimori

2024-11-22 10:27 UTC, CaviarChen requested changes
其他一些想法。不妨碍这个PR，可以以后考虑。
1. 我还是觉得wasm单独拎出一个CI比较奇怪。另外那个CI是为了整一个app的，而且很多 journey bitmap 相关的测试也在另外的那个CI里。
2. journey core 这个名字可能有一丢奇怪，不过也不是大问题，可以以后再改名。

2024-11-22 10:27 UTC, CaviarChen commented on .github/workflows/wasm.yml
> +          cache: true
flutter 相关的删掉吧。还挺慢的。

2024-11-22 10:27 UTC, CaviarChen commented on app/journey_core/src/utils.rs
> +}
重复代码？如果现在不方便dedup的话可以留个 TODO。（可能留在另外一边更好，那边是需要被删掉的）。

2024-11-24 09:19 UTC, tavimori commented
> 其他一些想法。不妨碍这个PR，可以以后考虑。
> 
> 1. 我还是觉得wasm单独拎出一个CI比较奇怪。另外那个CI是为了整一个app的，而且很多 journey bitmap 相关的测试也在另外的那个CI里。
> 2. journey core 这个名字可能有一丢奇怪，不过也不是大问题，可以以后再改名。

1. 打算等webview的东西稳定了以后再整合成一个CI吧。
2. 名字改了。

2024-11-24 10:05 UTC, CaviarChen approved these changes

2024-11-24 10:08 UTC, merged