WebView Phase1 (readonly rendering support)
MemoLanes/MemoLanes pull request #141
Opened 2024-12-10 12:47 UTC by tavimori

2025-01-02 13:27 UTC, CaviarChen requested changes

2025-01-02 13:27 UTC, CaviarChen commented on app/rust/src/renderer/map_server.rs
> +const JOURNEY_VIEW_HTML: &str = include_str!("../../../journey_kernel/examples/journey-view.html");
这一系列文件放在 `examples` 目录下感觉很不合理。
在看到这里之前我一直以为那个目录下的文件只是为了调试 `journey_kernel`准备的，都没有仔细review。

2025-01-02 13:27 UTC, CaviarChen commented on app/rust/src/renderer/map_server.rs
> +const MAPBOX_CSS: &str = include_str!("../../../journey_kernel/examples/mapbox-gl.css");
感觉直接复制一份 mapbox 到repo里也有些粗暴，个人感觉可能还是尝试这个前端库用下 yarn / npm 之类的管理下依赖更好。甚至可以直接配置webpack将所有 js、css 合并并inline到html中，这样你这里只需要给前端提供单个文件就行了。

2025-01-02 13:27 UTC, CaviarChen commented on app/setup_token.py
> +    token_path = os.path.join(script_dir, "journey_kernel/examples/token.json")
换成 web based 的地图后，整个项目应该只需要一处 mapbox 的 token了，感觉可以直接让rust去读这个 .env 文件（或者某个特殊的文件，比如这个token.json，但是这就需要让所有现有开发者调整一下）。然后删除整个 setup_token.py

2025-01-02 13:27 UTC, CaviarChen commented on app/pubspec.yaml
> +  webview_flutter: ^4.8.0
mapbox_maps_flutter 相关的依赖可以清掉了？

2025-01-02 15:04 UTC, tavimori commented on app/rust/src/renderer/map_server.rs
> +const JOURNEY_VIEW_HTML: &str = include_str!("../../../journey_kernel/examples/journey-view.html");
当时是的，但是现在就顺便拿来用了，好处是一份代码就都能用。

2025-01-02 15:12 UTC, tavimori commented on app/setup_token.py
> +    token_path = os.path.join(script_dir, "journey_kernel/examples/token.json")
rust侧这样调整是可以，目前我用 token.json 主要还是在 vs code静态调试方便。（可能是出于安全原因，vs code live server extension默认不支持请求 .xxx 这样的隐藏文件）

我现在这个页面配置的确刻意abuse了请求数量（js，css，以及加载token都是额外的请求）不过我目前的想法是这些本地请求都没有什么cost，但实实在在的简化了项目结构？不过也可以讨论。

2025-01-02 15:14 UTC, tavimori commented on app/pubspec.yaml
> +  webview_flutter: ^4.8.0
嗯，如果都没有问题就可以去掉。我之前是打算这个pr先把新的模块加进来，没有问题的话，下个pr再删flutter之前的东西（或者留一段时间过渡）。如果测试没问题的话，一起删掉也可以。
目前还保留了之前的 base_map.dart

2025-01-02 16:11 UTC, CaviarChen commented on app/rust/src/renderer/map_server.rs
> +const JOURNEY_VIEW_HTML: &str = include_str!("../../../journey_kernel/examples/journey-view.html");
改名字可以，单纯觉得 example 有些 misleading

2025-01-02 16:14 UTC, CaviarChen commented on app/setup_token.py
> +    token_path = os.path.join(script_dir, "journey_kernel/examples/token.json")
留一个 token.json 然后删掉别的也行。但是最后放在上级一点的目录而不是在 `journey_kernel/examples` 这种很深的路径里。如果实现上：读取env麻烦，且只能放在很深的目录，那么现有这个setup方式也行，就是其他文件好删了。

2025-01-02 16:30 UTC, tavimori commented on app/setup_token.py
> +    token_path = os.path.join(script_dir, "journey_kernel/examples/token.json")
那我打算rust侧改成读`.env`，然后留一个脚本生成`token.json`用来方便静态调试。这样其他开发者只需要维护`.env`不需要引入新的步骤，只有需要网页静态调试的开发者需要执行脚本生成`token.json`。

2025-01-05 16:52 UTC, tavimori commented
改用了webpack，代价是现在每个开发者都需要装yarn和webpack一整套了，增加了一些外部依赖。
（我的感觉是引入外部依赖会让项目变复杂，不过anyway）

2025-01-06 18:25 UTC, tavimori commented on app/setup_token.py
> +    token_path = os.path.join(script_dir, "journey_kernel/examples/token.json")
目前 `setup_token.py` 已经不需要跑了，但是保留了文件用于 `token.json` 生成。（仅用于 `journey_kernel`开发）

2025-01-06 18:26 UTC, tavimori commented on app/rust/src/renderer/map_server.rs
> +const MAPBOX_CSS: &str = include_str!("../../../journey_kernel/examples/mapbox-gl.css");
换成 webpack 打包嵌入了。

2025-01-06 18:27 UTC, tavimori commented on app/pubspec.yaml
> +  webview_flutter: ^4.8.0
已经移除 flutter 侧的旧代码。rust侧因为改动比较大，还涉及大量的渲染测试，排到下一轮重构吧（以及目前的api有很多需要重新命名。

2025-01-06 18:27 UTC, tavimori commented on app/rust/src/renderer/map_server.rs
> +const JOURNEY_VIEW_HTML: &str = include_str!("../../../journey_kernel/examples/journey-view.html");
已经改成`static`

2025-01-06 18:29 UTC, tavimori commented
目前flutter侧的代码清理差不多了，rust的代码下一轮pr再改。因为后面这波改动也不小，还需要确认下时光机的页面内刷新和实体机测试（特别是安卓）。

2025-01-07 16:30 UTC, tavimori commented
剩了个flutter的活可供完善：

1. 目前之前main map的camera view状态保存已经去除了，需要针对webview重新实现。目前js侧预留了`window.getCurrentMapView()`接口获取地图camera信息，并且url后可以增加hash参数用以设定地图加载时的初始时camera参数（在rust目录下运行`cargo run --example server`也可以看到用hash设置初始camera参数的例子）。

具体文档可以参照 https://github.com/tavimori/MemoLanes/tree/webview-phase1/app/journey_kernel 页面。

2025-01-27 14:49 UTC, CaviarChen approved these changes
This PR is still a bit messy, adds a lot of TODOs, and make the main branch less release ready. However, I think we should merge this PR and follow up these details later. This is still a huge improvement.

2025-01-27 14:49 UTC, merged