Cache
MemoLanes/MemoLanes pull request #59
Opened 2024-03-02 11:19 UTC by wuwenw

Add cache V0, where a cached bitmap for all finalized ongoing journey is stored in cached db

current cache design
read data
1. try to fetch bitmap from cache db
2.a. if no, then fetch bitmap from main db, store it to cache db
2.b. if yes, use cached bitmap
3. merge bitmap with ongoing journey

write data
1. When a journey is finalized in storage, it will be inserted into main db with txn
2. for V0, we simply delete cached bitmap
TODO: more fine-grained deletes for cache (V1)

2024-03-22 09:27 UTC, CaviarChen requested changes

2024-03-22 09:27 UTC, CaviarChen commented on app/rust/src/merged_journey_manager.rs
> +        _ => return Err(Error::new(ErrorKind::InvalidData, "Expected bitmap data").into()),
cache_db 里可以直接存 `JourneyBitmap`，就可以避免这个额外的错误情况。

2024-03-22 09:27 UTC, CaviarChen commented on app/rust/src/merged_journey_manager.rs
> +        JourneyData::Bitmap(bitmap) => journey_bitmap.merge(bitmap),
这里我们先新建了一个空的 `journey_bitmap`，然后把空的跟缓存里的merge一下，最后返回结果。为什么不直接返回缓存里取出的那个bitmap呢？

2024-03-22 09:27 UTC, CaviarChen commented on app/rust/src/merged_journey_manager.rs
> +                // If no rows found in cache, fetch from main db and cache the result
这一段比较怪。
第一个问题，`get_finalized_from_cachedb` 返回的Err包含两种意思，1.一切正常，只是缓存为空。2.比较严重的错误。着两种情况混在一起感觉不是很合适，而且这一切的逻辑在 `cache_db`。要理解这个函数的行为需要一路阅读代码。
第二个问题，这两类错误的区别方法是 e.to_string() 然后比较string。在编译期很难检查这段string的正确与否。（比如我现在从里面删掉一个空格，代码的行为就变了，但是编译时并不会发现）
更为合理的是把这个数据库相关的逻辑藏到`cache_db`中，然后对应的函数返回 `Result<Option<JourneyBitmap>>`。这样看到函数名，看到类型就基本上知道是怎么回事了。

2024-04-19 15:01 UTC, wuwenw commented on app/rust/src/merged_journey_manager.rs
> +                // If no rows found in cache, fetch from main db and cache the result
这样的话 Result<Option<JourneyBitmap>> 相当于套了两层？第一层是严重的err， 第二层是空缓存情况

string比较确实不行

2024-04-19 15:01 UTC, wuwenw commented on app/rust/src/merged_journey_manager.rs
> +        JourneyData::Bitmap(bitmap) => journey_bitmap.merge(bitmap),
这个和上面的问题是一样的吧 因为没有缓存里不是journey_bitmap，直接存journey_bitmap就不需要这步了

2024-04-29 01:11 UTC, closed without merging

2024-04-29 01:11 UTC, CaviarChen commented
Included in #81