fix Foreground Service
MemoLanes/MemoLanes pull request #61
Opened 2024-03-27 08:27 UTC by kuailezhiyuan

2024-03-27 13:19 UTC, CaviarChen requested changes

2024-03-27 13:19 UTC, CaviarChen commented on app/lib/gps_recording_state.dart
> +            return;
如果上面 notification permission 是用 Exception的话，这里这种情况应该也用？ 或者都不用？（可能更友好的是弹个窗，但是这是以后的事了）

2024-03-27 13:19 UTC, CaviarChen commented on app/lib/gps_recording_state.dart
>    }
这区区一行代码的抽象没必要，不如直接inline

2024-03-27 13:19 UTC, CaviarChen commented on app/android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION" />
我居然不知道要这个，好蠢。

2024-03-27 13:19 UTC, CaviarChen commented on app/android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
可以试试看没有这个但是有`FOREGROUND_SERVICE_LOCATION`会怎样。同理可以试试没有`ACCESS_BACKGROUND_LOCATION `?

2024-03-27 13:19 UTC, CaviarChen commented on app/android/app/src/main/AndroidManifest.xml
> +        </service>
我怀疑这个是不需要的，可以试试。因为这个`AndroidManifest.xml` 会跟 `Geolocator`插件里提供的合并。然后那个里面是有这段的。（最后的apk中也能看出来）

2024-03-28 06:28 UTC, kuailezhiyuan commented on app/lib/gps_recording_state.dart
> +            return;
已增加弹窗，并优化异常处理

2024-03-28 06:28 UTC, kuailezhiyuan commented on app/android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION" />
android 14 新增加的权限

2024-03-28 06:29 UTC, kuailezhiyuan commented on app/android/app/src/main/AndroidManifest.xml
> +        </service>
已测试 移除后无影响

2024-03-28 06:29 UTC, kuailezhiyuan commented on app/android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
FOREGROUND_SERVICE_LOCATION 在android 14后必须有 ACCESS_BACKGROUND_LOCATION 移除后测试无影响

2024-03-28 13:39 UTC, CaviarChen requested changes

2024-03-28 13:39 UTC, CaviarChen commented on app/lib/gps_recording_state.dart
> +            Fluttertoast.showToast(msg: "Location permission not granted");
这样写三次不如外面 catch exception 然后show一下exception？

2024-03-28 13:39 UTC, CaviarChen commented on app/lib/gps_recording_state.dart
> +          Fluttertoast.showToast(msg: "Please allow location permissions");
我怀疑这条根本看不到？直接跳setting去了

2024-03-29 15:07 UTC, CaviarChen approved these changes

2024-03-29 15:08 UTC, merged