Export gpx and kml data
MemoLanes/MemoLanes pull request #67
Opened 2024-04-07 05:33 UTC by kuailezhiyuan

2024-04-16 13:33 UTC, CaviarChen requested changes
基本问题不大。
有一点我觉得可以思考下：时间戳怎么办？
我们储存的数据为了隐私问题会去除时间戳，但是依旧有开始和结束的时间戳。
最简单的想法是，给第一个点和最后个点带上时间戳。
但是kml这种格式可能不行？
还有种是利用开始和结束，平均的生成中间的时间错（可能也不是很合适）。

2024-04-16 13:33 UTC, CaviarChen commented on app/rust/tests/import_export_data.rs
> +    assert_eq!(points2, points1);
都在比较两个版本了，不如直接比较内容而不是个数

2024-04-16 13:33 UTC, CaviarChen commented on app/rust/src/import_data.rs
> +
为啥突然把这个函数往上挪？

2024-04-16 13:33 UTC, CaviarChen commented on app/rust/src/export_data.rs
> +    // You can give it anything that implements `std::io::Write`.
这注释可以删了

2024-04-16 13:33 UTC, CaviarChen commented on app/rust/src/export_data.rs
> +    let mut elements = vec![Kml::Style(style)];
这个style不写的话文件合法吗？如果不合法的话可以使用默认的style吗？感觉这些自定义的并没有什么意义

2024-04-16 13:33 UTC, CaviarChen commented on app/rust/src/export_data.rs
> +    let _ = writer.write(&kml);
这里用 _ 忽略了错误？

2024-04-16 13:33 UTC, CaviarChen commented on app/rust/Cargo.toml
> +maplit = { version = "1.0", default-features = false }
引用这么个包就为了初始化hashmap方便一点感觉稍微有点过，其实这样可能就行：
```
HashMap::from([("key", "value"), ("k2", "v2")]);
```

2024-04-18 16:27 UTC, kuailezhiyuan commented on app/rust/src/export_data.rs
> +    let mut elements = vec![Kml::Style(style)];
可以的 已去除

2024-04-18 16:33 UTC, kuailezhiyuan commented
> 基本问题不大。 有一点我觉得可以思考下：时间戳怎么办？ 我们储存的数据为了隐私问题会去除时间戳，但是依旧有开始和结束的时间戳。 最简单的想法是，给第一个点和最后个点带上时间戳。 但是kml这种格式可能不行？ 还有种是利用开始和结束，平均的生成中间的时间错（可能也不是很合适）。

因为目前来说 不一定中间的点的时间是平均分布的（使用LocationManager的时候 在没有gps信号时会收不到坐标流）如果不是特别在意准确度可以。或者说 增加选项允许收集时间戳？用户开启时收集时间戳，导出时有时间戳就带着 没有就仅轨迹坐标？

2024-04-19 12:46 UTC, CaviarChen approved these changes

2024-04-19 12:46 UTC, merged