map track
MemoLanes/MemoLanes pull request #78
Opened 2024-04-22 14:29 UTC by kuailezhiyuan

2024-04-22 15:31 UTC, CaviarChen requested changes

2024-04-22 15:31 UTC, CaviarChen commented on app/lib/map.dart
> +          zoom = 16.0;
10.5 和 16 调过了？

2024-04-23 13:47 UTC, kuailezhiyuan commented on app/lib/map.dart
> +          zoom = 16.0;
是的 按照差不多的缩放级别测的

2024-04-23 13:52 UTC, CaviarChen commented
cc @MajorTomc

2024-04-23 13:52 UTC, merged