[WIP] Cache v1
MemoLanes/MemoLanes pull request #95
Opened 2024-06-24 07:21 UTC by wuwenw

change logic of caching ongoing journey: instead of resetting cache, we choose to merge with current.

WIP

still need to add merge logic in cache db and test cases

2024-07-02 13:55 UTC, CaviarChen requested changes

2024-07-02 13:55 UTC, CaviarChen commented on app/rust/src/main_db.rs
> +        merge_cache: bool,
我没有理解这个参数的作用。目前两个调用处都是用`false`。看上去这整段代码跟之前行为一致？

2024-07-02 13:55 UTC, CaviarChen commented on app/rust/src/main_db.rs
> +        self.reset_cache = !merge_cache;
缓存应该怎么处理应该是一个内部的事情，而不是一路由外部传进来。这里应该已经包含了所需的全部信息，为什么要从外部获得呢？如果暴露这样一个API，所有用到的地方都需要仔细review行为。

2024-07-02 13:55 UTC, CaviarChen commented on app/rust/src/storage.rs
> +                )?;
从这段代码来看，`merge_cache` 是指加入的旅程是timestamp上最新的一段？感觉设计比较奇怪，一切新增都可以走merge，而不是重建整个缓存。没有必要限制在最新一段？另外如果是如此的话`merge_cache`是一个比较差的名字，光看函数签名而不读整段代码的话完全无法理解在发生什么。（这也是为什么这个参数不应该暴露）

2024-07-02 13:55 UTC, CaviarChen commented on app/rust/src/main_db.rs
> +    pub merge_cache: bool,
`bool` 其实是个很糟的类型，相对来说没有那么清晰，尤其是在这里用两个 `bool`。
首先按你的设计，这里应该只需要三个状态
```
｜None
 | Merge_latest
 | Complete_rebuilt
```
而用两个 `bool` 的话就有四种状态了，有不需要的状态。所以用enum的话可以减少无效状态且更可读。

像我在其他comment里提到的，这里的merge latest非常奇怪，更完善的处理是:
```
｜None
 | Merge {journey_ids : Vec<String>}
 | Complete_rebuilt
```

如果要一步到位到最终的情况，这里其实应该是
```
enum Action {
｜None
 | Merge {journey_ids : Vec<String>}
 | Complete_rebuilt
}
```
然后储存一个叫 `actions` 之类的field，类型是 `Hashtbl<CacheKey, Action>`
(有几天没写rust syntax 有点忘了，大致是这个意思)
（现在阶段不需要这个hashtbl因为CacheKey只有一个可能）

2024-07-02 14:18 UTC, CaviarChen commented on app/rust/src/main_db.rs
> +        merge_cache: bool,
我瞎了

2024-07-02 14:22 UTC, CaviarChen commented on app/rust/src/main_db.rs
> +                    true,
比如这里就其实有问题，虽然 finalize_ongoing_journey 大概率是加一个最新的，但是没有地方确保这个真的成立。比如导入数据，调整系统时间之类的都有可能造成这个问题。这也就是为什么如果本身有足够的信息，就不应该去依赖别的。即便我们要选这个只支持merge最新一段旅程的设计，那么也应该在 `create_and_insert_journey` 之类的函数中自己判断新插入的是不是最新的。

2024-07-07 14:54 UTC, wuwenw commented
@CaviarChen 总结一下
用enum存merge {ids}， 把这个暴露给上一层，然后上层再传给cache db去merge对应的id？

2024-07-08 14:02 UTC, CaviarChen requested changes

2024-07-08 14:02 UTC, CaviarChen commented on app/rust/src/main_db.rs
> +        };
一个 transaction 内多次操作就不对了吧？另外这里的 Vec 也没有用到？

2024-07-08 14:02 UTC, CaviarChen commented on app/rust/src/storage.rs
> +                }
`Action` 给到 cache_db 然后让cache db内部处理更符合抽象一点。不过我这个感觉不是很强烈。

2024-07-08 14:02 UTC, CaviarChen commented on app/rust/src/storage.rs
> +                }
不太理解为什么 None 是出错？

2024-07-08 14:02 UTC, CaviarChen commented on app/rust/src/main_db.rs
> +
感觉现在用不到了？

2024-07-09 04:34 UTC, wuwenw commented on app/rust/src/storage.rs
> +                }
@CaviarChen 给到cache db里的话，get_journey不太好拿？

2024-07-11 13:12 UTC, CaviarChen approved these changes

2024-07-11 13:18 UTC, CaviarChen approved these changes

2024-07-11 13:19 UTC, merged